### ISSUE TITLE
Problems about the Figure 2 and 3D loss landscape

### ISSUE THREAD

**Issue by Billy1900** [wronnyhuang/gen-viz#1]
I have found your paper on Arxiv, and I really appreciate your work. However, it seems like your paper draft has lost figure 2. Besides, I wanna know how you could draw the 3D loss function landscape.
paper Link: https://arxiv.org/pdf/1906.03291.pdf

**Comment by wronnyhuang** [comment]
Thanks @Billy1900 for pointing out the broken references in our latest arxiv submission. I have reverted it to the previous, stable version for now. The 3D loss landscape graphics were made with a software called [ParaView](https://www.paraview.org/)

**Comment by Billy1900** [comment]
Thanks for your help. Would you mind giving me more specific instructions on paraview? I mean the data file, but not the operation.

**Comment by wronnyhuang** [comment]
To compute the loss landscape matrix, see instructions here https://github.com/wronnyhuang/gen-viz/tree/master/svhn.
As for how we actually plotted the matrix in ParaView, you will need to look through their [tutorials](https://www.paraview.org/Wiki/The_ParaView_Tutorial) as it's been a while since we have used it.

**Comment by Billy1900** [comment]
I think the point is the matrix. If you still store the data file or function, please send me one. My email: billyrobertluo@gmail.com

**Comment by wronnyhuang** [comment]
Unfortunately I don't have that file anymore. You will need to regenerate
it using surface.py

Ronny
